/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KostenRouteImport } from './routes/kosten'
import { Route as RittenRouteImport } from './routes/ritten'
import { Route as RittenIdRouteImport } from './routes/ritten.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KostenRoute = KostenRouteImport.update({
  id: '/kosten',
  path: '/kosten',
  getParentRoute: () => rootRouteImport,
} as any)
const RittenRoute = RittenRouteImport.update({
  id: '/ritten',
  path: '/ritten',
  getParentRoute: () => rootRouteImport,
} as any)
const RittenIdRoute = RittenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RittenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kosten': typeof KostenRoute
  '/ritten': typeof RittenRouteWithChildren
  '/ritten/$id': typeof RittenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kosten': typeof KostenRoute
  '/ritten': typeof RittenRouteWithChildren
  '/ritten/$id': typeof RittenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kosten': typeof KostenRoute
  '/ritten': typeof RittenRouteWithChildren
  '/ritten/$id': typeof RittenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kosten' | '/ritten' | '/ritten/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kosten' | '/ritten' | '/ritten/$id'
  id: '__root__' | '/' | '/kosten' | '/ritten' | '/ritten/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KostenRoute: typeof KostenRoute
  RittenRoute: typeof RittenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosten': {
      id: '/kosten'
      path: '/kosten'
      fullPath: '/kosten'
      preLoaderRoute: typeof KostenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritten': {
      id: '/ritten'
      path: '/ritten'
      fullPath: '/ritten'
      preLoaderRoute: typeof RittenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritten/$id': {
      id: '/ritten/$id'
      path: '/$id'
      fullPath: '/ritten/$id'
      preLoaderRoute: typeof RittenIdRouteImport
      parentRoute: typeof RittenRoute
    }
  }
}

interface RittenRouteChildren {
  RittenIdRoute: typeof RittenIdRoute
}

const RittenRouteChildren: RittenRouteChildren = {
  RittenIdRoute: RittenIdRoute,
}

const RittenRouteWithChildren =
  RittenRoute._addFileChildren(RittenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KostenRoute: KostenRoute,
  RittenRoute: RittenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
